fedora: updated hacking session
Change-Id: I640a1974a2bd31f4c0f1b7fcf713eebeee2168c1
Signed-off-by: Josep Puigdemont <josep.puigdemont@linaro.org>

diff --git a/setup_session_fedora b/setup_session_fedora
--- a/setup_session_fedora
+++ b/setup_session_fedora
@@ -6,9 +6,20 @@ cp stop_hacking_fedora /bin/stop_hacking
 chmod a+x invoke_session_fedora
 cp invoke_session_fedora /bin/invoke_session
 
-mkdir -p ~/.ssh/
+mkdir -m 700 -p ~/.ssh/
 echo $1 >> ~/.ssh/authorized_keys
+if [ $? -ne 0 ]; then
+    lava-test-case public-key-installed --result fail
+fi
+chmod 600 ~/.ssh/authorized_keys
 echo "Public Key Installed: $1"
+lava-test-case public-key-installed --result pass
 
-service sshd restart
-echo "sshd re-started"
+systemctl restart sshd
+if [ $? -eq 0 ]; then
+    lava-test-case sshd-restart --result pass
+    echo "sshd re-started"
+else
+    lava-test-case sshd-restart --result fail
+    echo "sshd re-start failed"
+fi
